### ISSUE TITLE
AR / Camera does not load the first time you grant the camera permission on Android

### ISSUE THREAD

**Issue by Crashthatch** [Unity-Technologies/experimental-ARInterface#11]
2nd time launching the app is fine.

To reproduce, close your app, go into Application Settings, revoke the "Camera" permission, then restart the app. You should be prompted to grant permission, but after pressing "Accept" the camera background does not display and AR movements are not detected.

Close (swipe away) and re-open the app and it will wok.

**Comment by jimmy-jam** [comment]
this should be fixed the above two merges
