### ISSUE TITLE
Enhancement: Add VisualizedPlane component with SetSize() fnx

### ISSUE THREAD

**Issue by treefortress** [Unity-Technologies/experimental-ARInterface#13]
In order to better display our plane previews, we don't really want to set scale on the PlanePreview directly, as that causes stretching and is inflexible.

I'd propose:
* ARPlaneVisualizer.m_PlanePrefab is a ARVisualizedPlane
* call m_PlanePrefab .SetSize(plane.extents) to set size
* SetSize() sizes the plane according to extents and it's own internal logic 

Then we can just subclass ARVisualizedPlane to have complete control over sizing and layout of our planes. Would also allow you to refactor your example to eliminate stretching of the borders.

**Comment by jimmy-jam** [comment]
ARPlaneVisualizer uses a prefab so that you can customize its appearance however you want - just put some scripting in your plane prefab that reads the parent size, etc.
