### ISSUE TITLE
Enhancement: Add More Display Options to ARPlaneVisualizer

### ISSUE THREAD

**Issue by treefortress** [Unity-Technologies/experimental-ARInterface#14]
There are a few different use cases for Plane Visualizations that would be nice to have supported. 

1. I want to see all the planes, all the time. (For testing, or some weird game that uses multiple planes)
2. I want to see only the plane I'm currently pointing at (when searching for one good plane)
3. I've chosen a plane, and would like to disable any others, so their collisions don't interfere, and they don't clutter my playspace. But still want collisions to work on my selected plane. (in game mode)

Perhaps some VisualizationType options:
* VisibilityType.ShowAll
* VisibilityType.ShowSingle
* VisibilityType.ShowNone

And then we need some way control colliders:
* CollisionType.EnableAll
* CollisionType.EnableSingle
* CollisionType.EnableNone

With the combination of those two settings, we should be able to get any behavior we need.

**Comment by iBicha** [comment]
I think the thing that you want to achieve can be solved by a simple raycast and enabling/disabling Renderers and Colliders etc. You have full control since you are able to define the plane prefab you want to use.

**Comment by jimmy-jam** [comment]
will not fix, as pointed out by iBicha, this seems like functionality that belongs at the application level
