### ISSUE TITLE
[Interface design] ARInterface design discussion

### ISSUE THREAD

**Issue by iBicha** [Unity-Technologies/experimental-ARInterface#15]
So far I was trying to use the interface in practical projects, and my thoughts about the interface are the following:

- [x] 1-IsSupported property #6 
- [ ] Adding an option to get the luminance only (or support a range of image formats, See ARCore Update below)
- [ ] Anchor support
- [x] `StartService` Async (See ARCore Update below)

1-The intention of the first one is pretty obvious, which is to display proper error messages, or even switch to an alternative SLAM technology, instead of limiting the range of devices an app can run on.

2-The second is an optimisation technique. Maybe 90% of the purpose of acquiring the camera image is to do additional computer vision computations. Most of the time, you start by getting a grey scale of the image. If that's the case, it would be a good optimisation not to copy the uv every frame, which can be a bit expensive.

I suggest changing this
`public abstract bool TryGetCameraImage(ref CameraImage cameraImage);`
to this
`public abstract bool TryGetCameraImage(ref CameraImage cameraImage, bool luminanceOnly = false);`

Which would only copy the Y component of the YUV buffer if luminanceOnly is true.

3-Anchors can be super useful in case of a shift in the tracking, typically used when spawning something. This should be considered since both libraries support it, through [ARAnchor](https://developer.apple.com/documentation/arkit/aranchor)  and [GoogleARCore.Anchor](https://developers.google.com/ar/reference/unity/class/google-a-r-core/anchor) (after all, if planes are tracked, why not anchored points)

**Comment by iBicha** [comment]
ARInterface Update: with the release of ARCore preview 2, and the changes made to the API, few things are to consider:

1-Since starting a session is an `AsyncTask` now, The start service function can become a `Coroutine` that we `yield return` until it's done, and then read the result from the interface (see if it's running or not). On platforms that return immediately, can be an `AsyncTask` as well, that is set ti done immediately.

2-Getting the camera image on ARCore has changed, now it returns the externally created texture, while offering two possible formats, a `32 bits RGBA` buffer, or an `8 bits GrayScaleone`, which goes to the point in the original thread about getting luminance only, because working with grayscale is very common in CV. I think a unified API would look like the following:

`public abstract bool TryGetCameraImage(ref CameraImage cameraImage, ImageFormat imageFormat);`

Where ImageFormat can be `RGBA`, `YUV` or `GrayScale`. Maybe it's up to the interface implementation to acquire the available format, and convert it to the requested one. Also, the fact that requesting an image and actually acquiring it not happening in the same frame is a bit disappointing, it leads to inconsistencies and latency, and therefore inaccurate additional CV work. It was probably an optimisation decision.

I already updated ARInterface to ARCore preview 2, and it looks like it works as expected, I didn't implement the CameraImage part yet, thought I could share these ideas first.

**Comment by Crashthatch** [comment]
I have been using AR-Interface and it works well cross platform. The only thing that broke when going from Android to iOS was that TryGetCameraImage is returning a different format (size?) image on iOS (I haven't looked into why yet). I agree with your proposal above for the unified TryGetCameraImage signature.

> I already updated ARInterface to ARCore preview 2, and it looks like it works as expected

Will these be committed to this repo soon? I would like to adopt preview-2, but don't want to repeat work that you've already done.

**Comment by iBicha** [comment]
I think the image size issue is because of the distortion matrix (from what I've noticed, iOS would give you the image as displayed (distorted) while Android would give you an undistorted version of it, I'm not sure though, need to double check) but I guess I wanted to discuss the interfere design before diving into the implementation. I'll fork this and commit the changes I made, maybe in few days after I get the ARCore 2 to return a YUV CameraImage.

**Comment by iBicha** [comment]
@Crashthatch created a PR #17 with `TryGetCameraImage` missing

**Comment by iBicha** [comment]
For the CameraImage part, I suggest changing the structure from 
```
public struct CameraImage
{
    public byte[] y;
    public byte[] uv;
    public int width;
    public int height;
}
```
to
```
public struct CameraImage
{
    public byte[] data;
    public TextureFormat format;
    public int width;
    public int height;
}
```
And that's because:

1. Having one buffer of data would allow easy handling
2. The `format` field can describe the layout of the `data` field
3. It's mostly useful in this format for additional CV work, but if it is for rendering purposes, can easily be used to make a texture using [LoadRawTextureData](https://docs.unity3d.com/ScriptReference/Texture2D.LoadRawTextureData.html) since we have the format, width, height and data, which is all the information we need to switch from a `CameraImage` to a texture in one line of code

**Comment by iBicha** [comment]
Luminance only option (for additional computer vision) is probably not the most optimal way to do it, and should be implemented in a native plugin. I guess I wasn't thinking.
**Anchor support would still be nice** since both ARCore and ARKit support it, and would improve user experience.
