### ISSUE TITLE
Not getting a video feed

### ISSUE THREAD

**Issue by thePostFuturist** [Unity-Technologies/experimental-ARInterface#19]
Running any of the example scenes using either 2017.2.0f3 or 2017.3.0f2 brings up the default blue screen instead of the video feed. Followed the steps of ARCore installation, running the scenes out of the box with the settings verified.

Google's ARCoreKit app works.

**Comment by AlienJim** [comment]
That's pretty vague. Got any logs from the device?

**Comment by jimmy-jam** [comment]
I cannot repro this either - any more information on this?

**Comment by jimmy-jam** [comment]
no repro
