### ISSUE TITLE
Scene Restart

### ISSUE THREAD

**Issue by StijnPaladin** [Unity-Technologies/experimental-ARInterface#30]
In our game AR is not the main mechanic but rather a small part of the game. As such we've put the AR in a separate scene that gets loaded and unloaded again when that part is done. When the scene gets loaded for the second time however we saw a black screen. This appears to be caused by a null reference in Google's code `SessionManager.cs:81`.

I think this is a problem of the `experimental-ARInterface` implementation though as `ARCoreInterface` seems to hold an invalid `m_SessionManager` which has been destroyed but not cleared.

I've fixed this by adding a line In `ARCoreInterface.cs`, function `StopService()`:
`m_SessionManager = null;`

**Comment by dive155** [comment]
StijnPaladin thank you. I've spent hours trying to figure out why ARCore wasn't working after scene change, your solution helped me to fix this issue.

**Comment by Crashthatch** [comment]
@dive155 Can you submit a PR or describe the complete change you had to make? I'm hitting the same issue.

**Comment by dive155** [comment]
@Crashthatch just as StijnPaladin suggested, i've added the line `m_SessionManager = null;` at the end of the `StopService()` function in `ARCoreInterface.cs`. It's the only relevant change, and after that my application started working fine.

**Comment by kolodi** [comment]
It is obviously a bug. Please add this fix to the code, it will save hours for other developers. I personally was debugging for at least 2 hours (and probably it would take another 2) if not this issue post :) Thx StijnPaladin

**Comment by Crashthatch** [comment]
@kolodi Send a pull-request if you're that desperate.

@dive155 / @StijnPaladin  thanks for the confirmation. I did do that but ended up hitting [this other 5 second-hang bug](https://github.com/google-ar/arcore-unity-sdk/issues/64). Are you not hitting this also? I've worked around it by staying in the same scene and just disabling / enabling objects to simulate changing scenes.

**Comment by cgfarmer4** [comment]
@Crashthatch I am hitting the 5 second bug. And a bit of a new one since adding the null in there.

```
02-07 11:15:45.861 26871 26871 I native  : session.cc:243 Session::Resume returning OK.
02-07 11:15:45.862 26871 26871 I Unity   : ArCoreUnity_resumeSession
02-07 11:15:45.862 26871 26871 E Unity   : Could not resume ARCore session because Unity is not ready to connect.
02-07 11:15:46.088 26871 26887 E native  : status.cc:134 ArStatusErrorSpace::AR_ERROR_NOT_YET_AVAILABLE
02-07 11:15:49.879 26871 26887 E CRASH   : backtrace:
02-07 11:15:49.882 26871 26887 E CRASH   : 	#00  pc 00018bd0   ( GoogleARCoreInternal.SessionManager:_EarlyUpdate (intptr,int) + 0x20 (0xdf01bbb0 0xdf01bc38) [0xe7187ee0 - Unity Root Domain]+101328)
```

**Comment by StijnPaladin** [comment]
I'm not experiencing this issue. I'm using a Pixel 2 phone and building with Unity 2017.3.0p2 targeting API level 27.

**Comment by StijnPaladin** [comment]
Opened a pull request: https://github.com/Unity-Technologies/experimental-ARInterface/pull/36

**Comment by cgfarmer4** [comment]
The issue occurs with Unity 2017.3.0p4 targeting API level 27 and a Pixel XL.

**Comment by lightbringer** [comment]
Funny. I literally fixed this issues the same way and came here to look if somebody came up with a better solution.

**Comment by jimmy-jam** [comment]
https://github.com/Unity-Technologies/experimental-ARInterface/pull/36 has been merged

**Comment by Saicopate** [comment]
Has this issue been really fixed? 
After scene reload I am getting null reference error in ARController.cs on `m_ARCamera` in `OnBeforeRender()` function. 

I can't really figure out why Main Camera (parented to AR Root gameObject) becomes missing when reloading the AR scene. On first scene load all works as it should. Only after quitting the AR scene and reentering it again the assigned Main Camera is gone. Still the backrender texture is displayed ok but there are no pose updates.

**Comment by cgfarmer4** [comment]
It never worked right for me until I got rid of this repo and moved to using ARCore without this interface. Unfortunate but it doesn’t seem Unity is interesting testing this repo very diligently. It does say experimental and the readme should say use at your own risk because PRs are often not tested correctly. All things considered, this repo was great when it first launched.

**Comment by Saicopate** [comment]
Yes **cgfarmer4**, I have seen your issue #43 and it seems true what you are saying that since replacing the SessionManager with ARCoreSession the `StopService()` method is broken.

`StopService()` is indeed launched by ARController.cs `OnDisable()` method when switching scene but it is not effective - I am getting null reference exception on `TextureReader_destroy();` line, which is really an extern function and I can't get past that.

I was hoping for using ARInterface in my app to spare time on later maintenance but now I've spent 1,5 day now trying to figure this out and maybe you are right that it is too experimental for now and we should switch to independent Unity plugins.

**Comment by cgfarmer4** [comment]
Ya if you need to get going now, I would go directly for the ARCore plugin and then port to iOS when 2018.1 stabilizes. I believe this repo is mostly untested because official support is coming in 2018.1. You can see it in the roadmap that they have outlined “Native Cross-Platform AR APIs”.
