### ISSUE TITLE
Can't build TanksNetworking on iOS

### ISSUE THREAD

**Issue by shekit** [Unity-Technologies/experimental-ARInterface#38]
Hi,

I'm trying to build the TanksNetworking demo on my iPhone running iOS 11.0.1 using Unity 2017.3.1f1, however the build keeps failing with this error:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ARWorldTrackingConfiguration", referenced from:
      objc-class-ref in ARSessionNative.o
  "_OBJC_CLASS_$_AROrientationTrackingConfiguration", referenced from:
      objc-class-ref in ARSessionNative.o
  "_OBJC_CLASS_$_ARAnchor", referenced from:
      objc-class-ref in ARSessionNative.o
  "_OBJC_CLASS_$_ARPlaneAnchor", referenced from:
      objc-class-ref in ARSessionNative.o
  "_OBJC_CLASS_$_ARSession", referenced from:
      objc-class-ref in ARSessionNative.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any ideas?

**Comment by jimmy-jam** [comment]
Those are symbols in ARKit.framework, so check:
-Are you using latest XCode 9.2?  
-Have you changed the project in any way?

**Comment by shekit** [comment]
Yes I am using XCode 9.2. The only change I made was replacing the event system references of the horizontal and vertical axis from HorizontalUI and VerticalUI to Horizontal and Vertical as it was causing errors otherwise errors.

In a slightly unrelated note, I can't seem to understand where in the code the level gets instantiated at the center of the detected plane?

**Comment by jimmy-jam** [comment]
You are trying to build to actual device, right?  Not simulator or generic?  Maybe update your iOS on your phone - 11.0.1 is pretty old.  Or try getting a clean copy of project and use unity 2017.1.

**Comment by shekit** [comment]
Yes I'm building to the device. I tried Unity 2017.1 on which it didn't work and then upgraded to 2017.3. I'll try updating iOS and seeing if that helps. 

Also could you point me in the direction of where to look for the level instantiation. Thanks!

**Comment by vlobanov** [comment]
If anyone is still facing the issue, in my case it helped to put "run in Xcode" to Release instead of Development

**Comment by kish3838** [comment]
I need "ARKit.framework" Please help.
