### ISSUE TITLE
Support ARCore 1.0

### ISSUE THREAD

**Issue by Crashthatch** [Unity-Technologies/experimental-ARInterface#40]
Blog Post: https://www.blog.google/products/google-vr/announcing-arcore-10-and-new-updates-google-lens/

Updated ARCore Unity SDK: https://github.com/google-ar/arcore-unity-sdk

**Comment by botaohu** [comment]
+1

**Comment by stella3d** [comment]
Hi, i'm doing this right now.  PR up soon.

**Comment by Britvich** [comment]
Excellent, looking forward to it.

**Comment by stella3d** [comment]
ARCore 1.0 support has now landed to master as seen above.  

We've tested the upgrade and the example scenes are working well.  Enjoy !
