### ISSUE TITLE
ARCore BuildHelper.cs doesn't compile with Unity 2018 Beta

### ISSUE THREAD

**Issue by Britvich** [Unity-Technologies/experimental-ARInterface#42]
In `GoogleARCore/SDK/Scripts/Editor/BuildHelper.cs`, the interface `IPreprocessBuild` has changed from:

`public void OnPreprocessBuild(BuildTarget target, string path)`

to

`public void OnPreprocessBuild(BuildReport report)`

**Comment by Britvich** [comment]
I added the following to my version:

```
#if UNITY_2018_1_OR_NEWER
    using UnityEditor.Build.Reporting;
#endif
```
and...

```
#if UNITY_2018_1_OR_NEWER
        public void OnPreprocessBuild(BuildReport report) {
#else
        public void OnPreprocessBuild(BuildTarget target, string path) {
#endif 
```

**Comment by stella3d** [comment]
PR has been accepted !
