### ISSUE TITLE
Integration with ORB-SLAM2

### ISSUE THREAD

**Issue by joduffy** [Unity-Technologies/experimental-ARInterface#47]
Hi,

This really isn't so much an issue as finding out whats involved in combining the two.
I have talked to the developers of:

[](https://github.com/raulmur/ORB_SLAM2)

They have a SLAM library for large scale tracking environments, since ARKit and ARCore are really only good for local AR experiences. 

In theory, combining ARInterface with this SLAM would allow you to map out a park, or a building for  greater AR experience over a sustained distance without drift. Their algorithm is free, except for commercial use. In that case, you will need to have a license - which is pretty expensive.

They did mention that I could create a unity plugin for their algorithm, and charge unity developers for it. The Unity developers wouldn't need to buy a license for using the plugin, since it would be going through my license.

I was curious if Unity would be interested in supporting this type of feature for its developers? I am happy to work alongside Unity on this as I feel it is something that we can all benefit from.

Apologies again if this was the wrong place to post/ask about this - I couldn't find the right channel to use. So I figured I would go straight to the AR Unity Dev Team.

**Comment by jimmy-jam** [comment]
Please post this on the unity forums in the appropriate sub forum.
