### ISSUE TITLE
AR Scene restart failure bug (replication scenario included)

### ISSUE THREAD

**Issue by Saicopate** [Unity-Technologies/experimental-ARInterface#59]
When starting scene containing AR content for the second time the camera pose updates are lost.

Scenario to replicate the bug:
1. Make a sample ("no-AR") scene containing only a button with a OnClick method switching to ARBallz scene
`SceneManager.LoadScene("ARBallz", LoadSceneMode.Single);`

2. Add a button to ARBallz scene switching back to "no-AR" scene
`SceneManager.LoadScene("no-AR", LoadSceneMode.Single);`

3, Remove "Don't Destroy on Load" component from AR Root in ARBallz scene

4. Add scenes to build settings and run on Android

When switching between the scenes, ARBallz scene works properly only when started for the first time.
This is very limiting because if you want to build a proper AR app there are high chances you will need to switch between non-AR and AR scenes.

**Comment by neeraj-bedi** [comment]
Just change replace   Application.onBeforeRender -= OnBeforeRender; before m_ARInterface.StopService();

 void OnDisable()
        {
            StopAllCoroutines();
            if (IsRunning)
            {
//Like this
                Application.onBeforeRender -= OnBeforeRender;
                m_ARInterface.StopService();
                
            }
           

        }

**Comment by Saicopate** [comment]
That fix seems to be working as needed! Thank you!
