### ISSUE TITLE
Scene reload causes the placement of a new plane to go wrong.

### ISSUE THREAD

**Issue by 10hijop10** [Unity-Technologies/experimental-ARInterface#60]
Everything seems to be working fine when I load the scene for the first time, but when I want to reload it so that you can place your plane somewhere else it gets bugged. This only happens after the game is build and played on mobile. When i reload the scene in the editor everything works like it should.

Any ideas?

**Comment by neeraj-bedi** [comment]
https://github.com/Unity-Technologies/experimental-ARInterface/issues/59 Please check this, this issue is solved

**Comment by 10hijop10** [comment]
thank you :) didn't see the post
